version: '3'
services:
  frontend:
    image: frontend:v1.0.0
    build:
      context: .
      dockerfile: ./CICD/frontend.Dockerfile
    volumes:
      - .:/frontend/
    ports:
      - "${FRONTEND_PORT}:80"
    expose:
      - 80